AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for the serverless NaoTomoriV2 Discord bot.

Parameters:
  MalClientId:
    Type: String
    Description: MAl client id.
    NoEcho: true
  MalUsername:
    Type: String
    Description: MAl username.
  MalPassword:
    Type: String
    Description: MAl password.
    NoEcho: true
  9AnimeUrl:
    Type: String
    Description: 9Anime URL.
  DiscordClientToken:
    Type: String
    Description: Discord client Token.
    NoEcho: true
  DiscordBotChannelId:
    Type: String
    Description: Discord channel id where the bot will message you.
    NoEcho: true
  DiscordUserId:
    Type: String
    Description: Your Discord user id.
    NoEcho: true

Resources:
  AnimeListSynchroniser:
    FunctionName: anime-list-synchroniser
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./code/functions/anime-list-synchroniser
      Handler: build/infrastructure/inbound/lambda/handler.lambdaHandler
      Runtime: nodejs16.x
      Events:
        AnimeListSynchroniseSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 hour)'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AnimeWatchingTable
      Environment:
        Variables:
          MAL_CLIENT_ID: !Ref MalClientId
          MAL_USERNAME: !Ref MalUsername
          MAL_PASSWORD: !Ref MalPassword
          ANIME_WATCHING_TABLE_NAME: !Ref AnimeWatchingTable

  AnimeEpisodeChecker:
    FunctionName: anime-episode-checker
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./code/functions/anime-episode-checker
      Handler: build/infrastructure/inbound/lambda/handler.lambdaHandler
      Runtime: nodejs16.x
      Events:
        AnimeEpisodeCheckerSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(10 minutes)'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AnimeWatchingTable
      Environment:
        Variables:
          ANIME_WATCHING_TABLE_NAME: !Ref AnimeWatchingTable
          NINE_ANIME_URL: !Ref 9AnimeUrl
          DISCORD_CLIENT_TOKEN: !Ref DiscordClientToken
          DISCORD_BOT_CHANNEL_ID: !Ref DiscordBotChannelId
          DISCORD_USER_ID: !Ref DiscordUserId

  AnimeWatchingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: anime-watching
      PrimaryKey:
        Name: Title
        Type: String
