name: SAM Pipeline

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Build and Test AnimeListSynchroniser
        run: |
          cd code/functions/anime-list-synchroniser
          npm i
          npm run build
          npm run test
      - name: Build and Test AnimeEpisodeChecker
        run: |
          cd code/functions/anime-episode-checker
          npm i
          npm run build
          npm run test
      - name: SAM build
        run: sam build --use-container --parameter-overrides \
              "MalClientId=${{ secrets.MAL_CLIENT_ID }} MalUsername=${{ secrets.MAL_USERNAME }} MalPassword=${{ secrets.MAL_PASSWORD }}" \
              "9AnimeUrl=${{ secrets._9_ANIME_URL }}" \ "
              "DiscordClientToken=${{ secrets.DISCORD_CLIENT_TOKEN }} DiscordBotChannelId=${{ secrets.DISCORD_BOT_CHANNEL_ID }} DiscordUserId=${{ secrets.DISCORD_USER_ID }}"
      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
